### PR TITLE
Navbar, index.html, css refactor

### PR DESCRIPTION
**Pull request by robinkwilson**
- Added responsiveness to index.html (previously named "IndividualToInfinity.html")

- Left Navbar icons use css animation to change size during hover
- Font scales depending on screensize: body sets the default font-size to 14px --> all cascading font-sizes uses em units as a percentage of the default

- Cleaned css code for left navbar and header
- Cleaned up unnecessary bootstrap html
- Cleaned up unnecessary js for animating navbar icons

- Reverted Avatar.html, js, css to previous version due to functionality bugs with the new css and js updates

### CODE REVIEW

**Comment by shashaxdu** [comment]
screen shot 2018-02-03 at 5 29 32 pm
screen shot 2018-02-03 at 5 41 03 pm

**Comment by shashaxdu** [comment]
screen shot 2018-02-03 at 5 52 47 pm

**Comment by shashaxdu** [comment]
screen shot 2018-02-03 at 6 08 05 pm

**Comment by robinkwilson** [comment]
I'm going to need to go in here and fix these into one standard div organization and styling. I'm working on brute forcing this to make it look good for this PR, but having issues that will be resolved when I focus on all of these buttons working in a standard way.

image

**Comment by robinkwilson** [comment]
I fixed this for now. I'll change the button width and height to adapt to the screen width in a future PR.

image

**Pull request merged**
